### ISSUE TITLE
withLive wrapper does not give updated state of code

### ISSUE THREAD

**Issue by anishagg17** [FormidableLabs/react-live#189] opened 2020-03-06 09:47 UTC
@sofiapoh i tried using withLive wrapper it provided only the initial code and not the newly created code 
Is there any way to get new code??

**Comment by sofiapoh** [comment] 2020-03-06 11:58
Could you provide with a minimal reproduction of the problem, either paste some code here or create a code sandbox. That way it's easier for me to see if the problem is with `react-live`

**Comment by anishagg17** [comment] 2020-03-06 12:04
https://github.com/FormidableLabs/react-live/blob/c4eee2cf08cb3600f62025f88016d8e2b3b9d3e5/stories/Live.js#L137


this live object has ` error and code ` as it's key .
`error` is updated each time any code change is made in the live editor but `code` remains the same as it was passed to LiveProvider

**Comment by anishagg17** [comment] 2020-03-06 12:05
What is to be done in order to get code written in the LiveEditor?

**Comment by sofiapoh** [comment] 2020-03-06 12:26
[Here](https://codesandbox.io/s/react-live-withlive-5fzge) is an example on how to use `react-live` and `withLive`. To keep track of the `code` you'll need to make it controlled from outside. I'm closing this issue as it's not a problem with `react-live  ` but I'll add some more examples to the readme.

**Closed by sofiapoh** 2020-03-06 12:26 UTC

**Comment by anishagg17** [comment] 2020-03-06 13:52
Thanks @sofiapoh
