### ISSUE TITLE
Theme not applied [v3.0.0]

### ISSUE THREAD

**Issue by areddon** [FormidableLabs/react-live#303] opened 2022-02-15 18:03 UTC
When supplying the `theme` to the `LiveProvider`, the styles it contains are incorrectly disregarded.

See the following [line](https://github.com/FormidableLabs/react-live/blob/master/src/components/Editor/index.js#L52).

`props.className` is coming in as undefined, while `_style` object contains `theme.plain` and therefore the expression will be true, yielding `{}` when you want `_style`.

**Comment by jpdriver** [comment] 2022-04-11 15:27
hey @areddon -- thanks for opening this issue! we're not aware of any issues passing `theme` down 🤔 

it's covered in one of our StoryBook [stories](https://github.com/FormidableLabs/react-live/blob/master/stories/Live.js#L250-L256) (which passes in the default theme [here](https://github.com/FormidableLabs/react-live/blob/master/src/constants/theme.js))

are you able to provide an example reproduction of what you're seeing? thanks!

**Comment by oliviadawd** [comment] 2022-10-18 18:53
I've noticed this as well when updating `react-live` from `2.4.1` to the latest (`3.1.1`). I tried passing the `vsDark` theme which worked in v2, but now it looks like this:

**vsdark theme on v2**
<img width="717" alt="Screen Shot 2022-10-18 at 2 49 59 PM" src="https://user-images.githubusercontent.com/8586077/196518338-ba79a873-3b3e-4ea7-ac45-6b84d101557c.png">

**vsdark theme on v3**
<img width="721" alt="image" src="https://user-images.githubusercontent.com/8586077/196517644-b8c9dd7b-c94d-4387-a734-8c6212e7497d.png">

it looks like the background color and the font-family isn't getting applied properly but the text colors look correct to me!

**Comment by GilmarLira** [comment] 2022-12-28 18:31
Our `prism-react-renderer` theme object is also not rendering correctly, after upgrading from `2.4.1` to `3.1.1`. To be specific, the issues seems limited to background color not propagating.

theme.js
```JSON
var theme = {
  plain: {
    plain: {
      backgroundColor: "#1f2a36"
    }
  }
}
```

### Before (`react-live@2.4.1`)
<img width="934" alt="Screenshot 2022-12-28 at 10 17 39" src="https://user-images.githubusercontent.com/4925585/209857025-b2e2f909-619e-463a-9a56-a1fb5dd33562.png">

### After (`react-live@3.1.1`)
<img width="933" alt="Screenshot 2022-12-28 at 10 20 22" src="https://user-images.githubusercontent.com/4925585/209857058-264c537f-b22b-4dab-814c-8a3e9773843b.png">

**Comment by GilmarLira** [comment] 2022-12-28 18:36
> hey @areddon -- thanks for opening this issue! we're not aware of any issues passing `theme` down 🤔
> 
> it's covered in one of our StoryBook [stories](https://github.com/FormidableLabs/react-live/blob/master/stories/Live.js#L250-L256) (which passes in the default theme [here](https://github.com/FormidableLabs/react-live/blob/master/src/constants/theme.js))
> 
> are you able to provide an example reproduction of what you're seeing? thanks!

@jpdriver, your StoryBook uses a styled Editor, which is defining a `background` [here](https://github.com/FormidableLabs/react-live/blob/5123cfd12de4cfafa7c65e59a967927a27eaca70/stories/Live.js#L78). It is therefore not really testing the `backgroundColor` coming from the theme. That is likely obscuring the issue @oliviadawd and myself are seeing.

**Comment by GilmarLira** [comment] 2022-12-28 19:15
Changing this line to use `LiveEditor` instead will reveal the problem:
https://github.com/FormidableLabs/react-live/blob/5123cfd12de4cfafa7c65e59a967927a27eaca70/stories/Live.js#L208

**Comment by ryan-roemer** [comment] 2022-12-30 18:48
Confirmed with following diff in default live example:

```diff
diff --git a/stories/Live.js b/stories/Live.js
index d29520b..29350de 100644
--- a/stories/Live.js
+++ b/stories/Live.js
@@ -226,6 +226,7 @@ export const Default = DefaultTemplate.bind({});
 Default.args = {
   ...defaultControls,
   code: code,
+  theme: theme,
 };
 
 export const FunctionExample = StyledPreviewTemplate.bind({});
```

Setting `theme.plain.color` does work, but setting  `theme.plain.backgroundColor` does not.

**Comment by cjseattle** [comment] 2023-06-09 19:00
Thanks for fixing this @ryan-roemer! I didn't realize it was fixed until I read through the releases, do you mind closing the issue?

**Closed** 2023-06-09 20:46 UTC
Labels: bug
