### ISSUE TITLE
facing some errors

### ISSUE THREAD

**Issue by anishagg17** [FormidableLabs/react-live#191] opened 2020-03-10 11:47 UTC
@sofiapoh I am facing some errors can you resolve them. I am providing this code to LivePreview

```
// import React, { Component } from 'react';

// import {
//   EuiButtonToggle,
//   EuiSpacer,
//   EuiTitle,
// } from '@elastic/eui';

 class extends Component {
  constructor(props) {
    super(props);

    this.state = {
      toggle0On: false,
      toggle1On: false,
      toggle2On: false,
      toggle3On: true,
      toggle4On: true,
    };
  }

  onToggle0Change = e => {
    this.setState({ toggle0On: e.target.checked });
  };

  onToggle1Change = e => {
    this.setState({ toggle1On: e.target.checked });
  };

  onToggle4Change = e => {
    this.setState({ toggle4On: e.target.checked });
  };

  render() {
    return (
      <div>
        <EuiButtonToggle
          label="Toggle Me"
          iconType={this.state.toggle0On ? 'starPlusEmpty' : 'starFilledSpace'}
          onChange={this.onToggle0Change}
          isSelected={this.state.toggle0On}
        />
        &emsp;
        <EuiButtonToggle
          label={
            this.state.toggle1On
              ? "I'm a filled toggle"
              : "I'm a primary toggle"
          }
          fill={this.state.toggle1On}
          onChange={this.onToggle1Change}
          isSelected={this.state.toggle1On}
        />
        &emsp;
        <EuiButtonToggle
          label="Toggle Me"
          iconType={this.state.toggle4On ? 'eye' : 'eyeClosed'}
          onChange={this.onToggle4Change}
          isSelected={this.state.toggle4On}
          isEmpty
          isIconOnly
        />
        <EuiSpacer size="m" />
        <EuiTitle size="xxs">
          <h3>Disabled</h3>
        </EuiTitle>
        <EuiSpacer size="s" />
        <EuiButtonToggle
          isDisabled
          label="Can't toggle this"
          fill={this.state.toggle2On}
          isSelected={this.state.toggle2On}
        />
        &emsp;
        <EuiButtonToggle
          isDisabled
          label="Can't toggle this either"
          fill={this.state.toggle3On}
          isSelected={this.state.toggle3On}
        />
      </div>
    );
  }
}

```

It generates this error 

```


SyntaxError: Unexpected token (22:18)
18 :       toggle4On: true,
19 :     };
20 :   }
21 : 
22 :   onToggle0Change = e => {

```

**Comment by sofiapoh** [comment] 2020-03-10 12:16
Hi, you're using the class fields syntax for declaring your functions which is not supported by `buble` without some extra code added. [Here](https://codesandbox.io/s/7ml9mjw766?fontsize=14) is an example on how to get `react-live` working with that specific syntax. Otherwise you could take the more traditional approach to declaring your class fields and refactor your functions to look like this: 

```
// import React, { Component } from 'react';

// import {
//   EuiButtonToggle,
//   EuiSpacer,
//   EuiTitle,
// } from '@elastic/eui';

 class extends Component {
  constructor(props) {
    super(props);

    this.state = {
      toggle0On: false,
      toggle1On: false,
      toggle2On: false,
      toggle3On: true,
      toggle4On: true,
    };

    this.onToggle0Change = this.onToggle0Change.bind(this);
    // Do this for the rest of the functions too

  }

  onToggle0Change (e) {
    this.setState({ toggle0On: e.target.checked });
  };
  
  // rest of the toggle functions

  render() {
    return (
      <div>
        <EuiButtonToggle
          label="Toggle Me"
          iconType={this.state.toggle0On ? 'starPlusEmpty' : 'starFilledSpace'}
          onChange={this.onToggle0Change}
          isSelected={this.state.toggle0On}
        />
       {/*....rest of the code*/}
      </div>
    );
  }
}
```

Closing this issue as it's not a bug with `react-live`

**Closed by sofiapoh** 2020-03-10 12:16 UTC

**Comment by anishagg17** [comment] 2020-03-10 13:57
Than you very much @sofiapoh
