### ISSUE TITLE
onChange LiveEditor

### ISSUE THREAD

**Issue by Flo-Slv** [FormidableLabs/react-live#73] opened 2018-04-27 11:35 UTC
Hi,

i have an issue when i try to add 'onChange' listener on LiveEditor. I want to save in my state the content.

Issue:
i change text of my second LiveEditor, then i change text of my first LiveEditor and the focus return to my second LiveEditor... :/

Have you an idea of what's wrong with my code? Thanks

This is my code:
ChallengeLiveCoding.js
```
import React from 'react';

import withAuth from '../../../hoc/withAuth';
import Layout from '../../../container/adminLayout';

import LiveEdit from './liveEdit';

class ChallengeLiveCoding extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      description: '',
      details: '',
      prizeDescription: '',
      companyVision: '',
      steps: '',
      legal: ''
    };
  }

  liveCodeChanges = (e, type) => {
    if (type === 'description')
      this.setState({
        description: e.trim()
      });
    else if (type === 'details')
      this.setState({
        details: e.trim()
      });
  };

  render() {
    const liveCode = type => `
      render(
        <div className="${type}">
          INSERER ICI VOTRE CODE HTML
        <style jsx>{\`
          .${type} {
            color: green;
          }
        \`}</style>
        </div>
      )
    `;

    return (
      <React.Fragment>
        <Layout {...this.props} navmenu>
          <BreadCrumb />
          <h3>Description</h3>
          <LiveEdit
            code={liveCode('description')}
            noInline
            change={this.liveCodeChanges}
            type="description"
          />
          <h3>Details</h3>
          <LiveEdit
            code={liveCode('details')}
            noInline
            change={this.liveCodeChanges}
            type="details"
          />
        </Layout>
      </React.Fragment>
    );
  }
}

export default withAuth(ChallengeLiveCoding);
```

liveEdit.js
```
import React from 'react';
import { LiveProvider, LiveEditor, LiveError, LivePreview } from 'react-live';

const LiveEdit = ({ code, noInline, change, type }) => (
  <div className="globalWrapper">
    <LiveProvider code={code} noInline={noInline}>
      <div className="liveWrapper">
        <LiveEditor className="styledEditor" onChange={e => change(e, type)} />
        <LivePreview />
      </div>

      <LiveError />
    </LiveProvider>
    <style jsx>{globalWrapper}</style>
  </div>
);
```

**Comment by Flo-Slv** [comment] 2018-04-30 12:28
In fact, onChange event return a string not an event object...

**Comment by kitten** [comment] 2018-08-17 14:19
Sorry for the late reply. This will receive more attention in the near future.

Duplicate of https://github.com/FormidableLabs/react-live/issues/28

**Closed by kitten** 2018-08-17 14:19 UTC

**Comment by wulucxy** [comment] 2019-03-09 05:58
@kitten still get the problem。

can‘t get the updated `code` value in context when `onChange` fired。

the `code` value is always intialValue，this is not expected。
