### ISSUE TITLE
v3 - Issues with Sucrase and esbuild (and webpack)

### ISSUE THREAD

**Issue by selbekk** [FormidableLabs/react-live#306] opened 2022-03-15 09:13 UTC
I've spend the better part of my morning trying to figure out why my Remix build doesn't want to play nice with react-live. [Here's the issue](https://github.com/remix-run/remix/issues/2321) I posted to the Remix repo.

In v1.2.2, they upgraded their dependency on esbuild to a version that doesn't work with Sucrase, since they don't accept their way of transpiling exports.

Not sure how we can fix this?

**Comment by nihgwu** [comment] 2022-03-22 13:21
https://github.com/nihgwu/react-runner/blob/master/examples/with-vite/vite.config.ts#L10

**Comment by jpdriver** [comment] 2022-04-05 02:45
per [this comment](https://github.com/evanw/esbuild/issues/2128)

> If you want to import ./NameManager.mjs you should import ./NameManager.mjs, not ./NameManager

it seems like this issue (whether it's Remix / Create React App / Vite / etc.) is caused by `sucrase` importing without the file extension 😔

---

@nihgwu has proposed splitting ESM exports out to a separate file in https://github.com/alangpierce/sucrase/pull/684 which seems to make a lot of sense. Let's hope the `sucrase` maintainers can take a look soon!

in the meantime @nihgwu has also published `sucrase-esm` https://www.npmjs.com/package/sucrase-esm based on those same changes..

until the way `sucrase` itself gets built has been updated, i'd suggest taking a look at that. you should be able to swap `sucrase` out for `sucrase-esm` in `react-live`'s dist using `patch-package` 🙇🏻‍♂️ 

---

as this isn't a direct issue with `react-live` and some environments -- like Next.js apps for instance -- work fine with `sucrase` even as-is, i'm going to close this issue off..

could also be worth noting that `react-live@latest` (v2.4.1) still uses Babel and should work. only `react-live@next` (v3.0.0+) uses Sucrase.

**Closed by jpdriver** 2022-04-05 02:45 UTC

**Comment by jpdriver** [comment] 2022-04-06 17:47
@selbekk just published `v3.1.0` which includes the updated version of `sucrase`

i can't exhaustively test _every_ setup, but i believe this should solve the issue you were seeing with Remix.

you can try it out using `yarn add react-live@next` if you'd like 🙇🏻‍♂️

**Comment by selbekk** [comment] 2022-04-06 17:48
I won't explicitly tell you I love you with all of my heart, but I will definitely insinuate it. Thanks a ton, will give it a shot right away!

**Comment by jpdriver** [comment] 2022-04-06 17:50
honestly all i've done here was bump a dependency 😅 the real fix was made by @nihgwu in `sucrase` so all credit goes to him

let me know how you get on!

**Comment by selbekk** [comment] 2022-04-06 18:31
It did indeed fix the issue I was running into. Thanks to @nihgwu's fantastic work, and your quick bump 🙌🏻 Onto the next blocker 🍡
